export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const INCREMENT_FIVE_COUNTER = 'INCREMENT_FIVE_COUNTER';
export const RESET_COUNTER = 'RESET_COUNTER';